### ISSUE TITLE
Import paths are case-sensitive but small letters used

### ISSUE THREAD

**Issue by lealem47** [angeloron/react-material-ui-stripe-payment-form#20]
For eg, in App,js, Header should be imported with `import Header from "./Views/Header";` and not `import Header from "./views/Header";`

This prevents these types of failures:

```
Failed to compile.
Cannot find file: 'Header.js' does not match the corresponding name on disk: '.\src\view\View
```

**Comment by angeloron** [comment]
Thank you for letting me know. Would you mind submitting a push with these changes and I can just merge it with the master?

**Comment by lealem47** [comment]
Ahh apologies. I was on a stale master and it seems the issue has been addressed.
