### ISSUE TITLE
feat: do not loose payment data when leaving the step

### ISSUE THREAD

**Issue by pefi1011** [angeloron/react-material-ui-stripe-payment-form#3]
Hi @angeloron 
thanks for your blog post and this repo. 

In my project, I had a use case where the step for payment data is not the last step. So what happened is that when a user leaves the step, all payment data is lost since the `StepContent` is unmounted. You can try it in your demo.
- Fill in all data
- Go back from the payment step to service step
- Go back from the service step to the payment step
- Credit card data is lost

Reason: `StepContent` is being unmounted & mounted => new iFrame is loaded every time you visit the payment step.

You can pass `TransitionProps={{ unmountOnExit: false }}` as prop for the StepContent. This can downgrade the performance, so you would like to do it only for the PaymentStep.

Cheers,

**Comment by angeloron** [comment]
Hey @pefi1011,
I am glad you liked my blog and repo and wow! thank you for your input, that's a great idea.
Do you feel like doing a pull request with that change?

**Comment by pefi1011** [comment]
Hi @angeloron 
the change includes a bit more refactoring since the the current code base is not using the [StepContent](https://material-ui.com/api/step-content/#stepcontent-api) component. Unfortunately, I do not have time to play with in upcoming weeks. If it helps you, here is my code which shows how is this done

```

<Stepper activeStep={step} orientation="vertical" className={classes.stepper}>

              {stepTitles.map((title, stepNumber) => {

                const labelErrorProps = {};
                const isStepFailed = this.isStepFailed(stepNumber);

                if (isStepFailed) {

                  labelErrorProps.optional = (
                    <Typography variant="caption" color="error">
                      {"The step contains errors. Please double-check here"}
                    </Typography>
                  );

                  labelErrorProps.error = true;
                };

                return (
                  <Step key={title} >
                    <StepLabel {...labelErrorProps}>{title}</StepLabel>
                    <StepContent TransitionProps={{ unmountOnExit: !this.isPaymentStep(stepNumber) }}>
                      {this.getStep(stepNumber)}
                      {this.getStepActions(stepNumber)}
                      {this.getStepActionHints(isStepFailed)}
                    </StepContent>
                  </Step>
                )
              })}

            </Stepper>


```

**Comment by angeloron** [comment]
Sorry for the huge delay in answering you. I checked into it and the only thing I could come up with is to keep the credit card data temporarily in your store and then load them back into the Stripe components once you arrive to that step. That should work out fine.
