### ISSUE TITLE
Styling doesn't work

### ISSUE THREAD

**Issue by hotcakedev628** [angeloron/react-material-ui-stripe-payment-form#5]
Hi @angeloron
Thanks for your blog post and this repo.

I was unable to style the Stripe components.

![image](https://user-images.githubusercontent.com/60177750/102908885-1a070800-4446-11eb-960b-70d92f0d3d49.png)

If I followed the code exactly the same, then how are you going to style the components, and how to set the current theme to the components?

**Comment by angeloron** [comment]
Hey, tks for your message and I am glad that you like my repo.
To style the stripe components you need to follow the documentation for
textField on material-ui as that is the library I am using.
On the screenshot you included it seems like you managed to change the
colors. What else do you want to change on the style?
Let me know and I can probably give you more specifics on what to do.

**Comment by hotcakedev628** [comment]
Thanks for your quick response.
What I want to change on the style is just to style the current theme to the Material UI `TextField` Stripe components.
Actually, I am using [Devias theme kit pro](https://material-ui.com/store/items/devias-kit-pro/), you could check the `Live Preview`.

**Comment by angeloron** [comment]
Thank you for your answer and merry Christmas. I checked the Live Preview and the only difference that I could see between the screenshot you sent me and that Live Preview is the font color which is black instead of grey. Is that correct? If not, please let me know exactly what you are trying to change on the style or ideally send me a codepen of what you are trying to program so I can play with the code.

**Comment by hotcakedev628** [comment]
Thank you @angeloron Merry Christmas.
The Devias Theme Kit provides three themes, the first one is `light`, second one is `dark`, the last one is `unicorn` mode.
You could check them by changing the settings. My screenshot refers to the `dark` mode.
Regarding your code, I have a stripe input component.
```
import React, { useRef, useImperativeHandle } from 'react'

const StripeInput = ({ component: Component, inputRef, ...other }) => {
  const elementRef = useRef();

  useImperativeHandle(inputRef, () => ({
    focus: () => elementRef.current.focus
  }));

  return (
    <Component
      onReady={element => (elementRef.current = element)}
      {...other}
    />
  );
}

And the component is using in my acceptance for an invoice component. (I am also using Formik.)
```
                  <TextField
                    error={Boolean(touched.CardNumber && errors.CardNumber)}
                    label="Credit Card Number"
                    name="cardNumber"
                    variant="outlined"
                    required
                    fullWidth
                    helperText={touched.cardNumber && errors.cardNumber}
                    InputProps={{
                      inputComponent: StripeInput,
                      inputProps: {
                        component: CardNumberElement
                      },
                    }}
                    value={values.cardNumber}
                    onChange={(value) => setFieldValue('cardNumber', value)}
                    InputLabelProps={{ shrink: true }}
                  />
```

export default StripeInput
```

I think you could let me know just how to style.
What I tried to code is to style the stripe input component like this.
```
    <Component
      onReady={element => (elementRef.current = element)}
      style={{
          base: {
            fontSize: `${theme.typography.fontSize}px`,
            fontFamily: theme.typography.fontFamily,
            color: '#000000de',
          },
       }}
      {...other}
    />
```
But it was not working.
I want to apply the current theme styles like font color, size, etc to the `TextField` material ui component.
Thank you again and have a great Christmas.

**Comment by angeloron** [comment]
Try to put the style in <TextField /> instead of <Component />. Here is the
Stripe documentation on that subject: Stripe: JavaScript SDK documentation
& reference <https://stripe.com/docs/js/element/the_element_container>

**Comment by hotcakedev628** [comment]
Is there any way to apply Material UI custom styles?

**Comment by angeloron** [comment]
I gave it a shot and it indeed seems to be a bit tricky. At the end I made it work using this [example](https://gist.github.com/HaNdTriX/ab9dd2f6d2c3045f55c7b3f541b03941)

**Comment by hotcakedev628** [comment]
> I gave it a shot and it indeed seems to be a bit tricky. At the end I made it work using this [example](https://gist.github.com/HaNdTriX/ab9dd2f6d2c3045f55c7b3f541b03941)

Thanks, @angeloron
